### ISSUE TITLE
Nugetizer seems to change AssemblyName of projects to the project's file name in dependency graph

### ISSUE THREAD

**Issue by karpis** [devlooped/nugetizer#270]
## Describe the Bug

This is a weird one. When having a project reference to another project that references the Nugetizer package, in dotnet's dependency graph the reference's assembly name is changed to the file name of the reference:

![image](https://user-images.githubusercontent.com/580842/212896493-64f441b4-0e95-4ba1-8fcf-e442dff4144f.png)

## Steps to Reproduce
Imagine two libraries. The first has a package reference to Nugetizer. The second doesn't. Also note the assembly names defined:

`LibraryWithNugetizer.csproj`
```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <AssemblyName>NugetizerLib</AssemblyName>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="NuGetizer" Version="0.9.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>
</Project>
```
`Library.csproj`
```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <AssemblyName>JustLib</AssemblyName>
    </PropertyGroup>
</Project>
```

And then a project that has project references to these libraries:

`TheConsumer.csproj`
```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
      <ProjectReference Include="..\Library\Library.csproj" />
      <ProjectReference Include="..\LibraryWithNugetizer\LibraryWithNugetizer.csproj" />
    </ItemGroup>
</Project>
```

When building _TheConsumer_, the dependency graph that dotnet generates is as follows (`TheConsumer.deps.json` in the build output directory):
```json
{
  "runtimeTarget": {
    "name": ".NETCoreApp,Version=v7.0",
    "signature": ""
  },
  "compilationOptions": {},
  "targets": {
    ".NETCoreApp,Version=v7.0": {
      "TheConsumer/1.0.0": {
        "dependencies": {
        "JustLib": "1.0.0",
        "LibraryWithNugetizer.csproj": "1.0.0",
        },
        "runtime": {
          "TheConsumer.dll": {}
        }
      },
      "JustLib/1.0.0": {
        "runtime": {
          "JustLib.dll": {}
        }
      },
      "LibraryWithNugetizer.csproj/1.0.0": {
        "runtime": {
          "NugetizerLib.dll": {}
        }
      }
    }
  },
  "libraries": {
    "TheConsumer/1.0.0": {
      "type": "project",
      "serviceable": false,
      "sha512": ""
    },
    "JustLib/1.0.0": {
      "type": "project",
      "serviceable": false,
      "sha512": ""
    },
    "LibraryWithNugetizer.csproj/1.0.0": {
      "type": "project",
      "serviceable": false,
      "sha512": ""
    }
  }
}
```

Notice that the assembly name of the second reference is _LibraryWithNugetizer.csproj_, not _NugetizerLib_.

Normally, this has no practical implications. Everything builds correctly, and all dlls are copied to the output directory. But in my case, _TheConsumer_ uses reflection and tries to load all of the referenced projects' assemblies by assembly name using:

```c#
Microsoft.Extensions.DependencyModel.DependencyContext
    .Load(Assembly.GetEntryAssembly()).RuntimeLibraries
    .Where(l => l.Type.Equals("project", StringComparison.InvariantCultureIgnoreCase))
    .Select(l => Assembly.Load(l.Name))
    .ToList();
```
which results in the following exception:
```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'LibraryWithNugetizer.csproj, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'LibraryWithNugetizer.csproj, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
   at System.Reflection.Assembly.Load(String assemblyString)
   at Program.<>c.<<Main>$>b__0_1(RuntimeLibrary l) in C:\Temp\bug\Example\TheConsumer\Program.cs:line 9
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.ToList()
   at Program.<Main>$(String[] args) in C:\Temp\bug\Example\TheConsumer\Program.cs:line 6
```

This is because `LibraryWithNugetizer.csproj` has an assembly name of `NugetizerLib`, hence it's not found.

## Expected Behavior

The assembly name of a project that references Nugetizer should not change for projects that reference it.

## Version Info

Nugetizer 0.9.1
dotnet 7.0.102

**Comment by kzu** [comment]
[NuGetized.zip](https://github.com/devlooped/nugetizer/files/10439858/NuGetized.zip)

Used the repro steps to recreate the structure, did the build on TheConsumer, I cannot repro.

deps file is as expected:

```
{
  "runtimeTarget": {
    "name": ".NETCoreApp,Version=v7.0",
    "signature": ""
  },
  "compilationOptions": {},
  "targets": {
    ".NETCoreApp,Version=v7.0": {
      "TheConsumer/1.0.0": {
        "dependencies": {
          "JustLib": "1.0.0",
          "NugetizerLib": "1.0.0"
        },
        "runtime": {
          "TheConsumer.dll": {}
        }
      },
      "JustLib/1.0.0": {
        "runtime": {
          "JustLib.dll": {}
        }
      },
      "NugetizerLib/1.0.0": {
        "runtime": {
          "NugetizerLib.dll": {}
        }
      }
    }
  },
  "libraries": {
    "TheConsumer/1.0.0": {
      "type": "project",
      "serviceable": false,
      "sha512": ""
    },
    "JustLib/1.0.0": {
      "type": "project",
      "serviceable": false,
      "sha512": ""
    },
    "NugetizerLib/1.0.0": {
      "type": "project",
      "serviceable": false,
      "sha512": ""
    }
  }
}
```

dotnet 7.0.100

**Comment by karpis** [comment]
You're completely right. This works as intended from the command line and in Visual Studio. So this is obviously a bug in JetBrains Rider.

Sorry for wasting your time! I'll file a bug with the Rider team.
